# Generated by Django 4.2.2 on 2023-10-15 00:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(default='Nome completo do aluno', max_length=120, verbose_name='Nome completo do aluno*')),
                ('nome_social', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento*')),
                ('idade', models.IntegerField(blank=True, null=True)),
                ('tel_celular_aluno', models.CharField(default='Celular 01', max_length=30, verbose_name='Nº de telefone do aluno*')),
                ('email', models.EmailField(max_length=200, verbose_name='Email*')),
                ('nome_mae', models.CharField(default='Nome completo da Mãe', max_length=120, verbose_name='Nome da Mãe*')),
                ('tel_celular_mae', models.CharField(default='Telefone da mae', max_length=30, null=True, verbose_name='Nº do celular do mãe*')),
                ('nome_pai', models.CharField(default='Nome completo da Pai', max_length=120, null=True)),
                ('tel_celular_pai', models.CharField(default='Telefone do pai', max_length=30, null=True)),
                ('naturalidade', models.CharField(default='Cidade onde nasceu', max_length=30)),
                ('data_entrada_no_pais', models.DateField(blank=True, null=True)),
                ('documento_estrangeiro', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_sanguineo', models.CharField(choices=[('6', 'AB-'), ('1', 'A+'), ('5', 'AB+'), ('7', 'O+'), ('4', 'B-'), ('8', 'O-'), ('3', 'B+'), ('0', 'Não informado'), ('2', 'A-')], max_length=3, null=True)),
                ('beneficiario_aux_Brasil', models.BooleanField(default=False, null=True, verbose_name='Selecione se o aluno é beneficiário do Bolsa Família/Aux. Brasil')),
                ('necessita_edu_especial', models.BooleanField(default=False, null=True, verbose_name='Selecione se o aluno precisa de algum atendimento especial')),
                ('sindrome_de_Down', models.BooleanField(default=False, null=True, verbose_name='Selecione se o aluno for portador de Síndrome de Down')),
                ('quilombola', models.BooleanField(default=False, null=True, verbose_name='Selecione se o aluno possui deficiência')),
                ('irmao_gemeo', models.BooleanField(default=False, null=True, verbose_name='Selecione se o aluno possui irmão(s) gêmeos')),
                ('vacina_covid_19', models.BooleanField(default=False, null=True, verbose_name='Selecione se o aluno tomou vacina contra a covid 19')),
                ('dose_vacina_covid_19', models.IntegerField(blank=True, null=True, verbose_name='Preencha se o aluno tomou alguma dose da covid 19')),
            ],
        ),
        migrations.CreateModel(
            name='AnoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliativa', models.BooleanField()),
                ('pontuacao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Compatibilidade_EducaCenso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('nivel', models.CharField(choices=[('1', 'Médio'), ('2', 'Superior')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Deficiencia_aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem_historico', models.IntegerField(null=True)),
                ('n_A', models.BooleanField(default=False, null=True, verbose_name='Destacar como N/S (Não avaliado) nos impressos')),
                ('faltas', models.BooleanField(default=False, null=True, verbose_name='Não permitir lançamento de faltas')),
                ('notas', models.BooleanField(default=False, null=True, verbose_name='Não permitir lançamento de notas')),
                ('historico_escolar', models.BooleanField(default=False, null=True, verbose_name='Não mostrar no histórico escolar')),
                ('papeletas', models.BooleanField(default=False, null=True, verbose_name='Não mostrar em papeletas')),
                ('ata_final', models.BooleanField(default=False, null=True, verbose_name='Não mostrar em Atas Finais')),
            ],
            options={
                'ordering': ['ordem_historico'],
            },
        ),
        migrations.CreateModel(
            name='Etnia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Faculdades_ou_Escolas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GrauEscolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Grau/Nível Escolar')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pais_origem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Remanejamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Ativo', 'Na Turma'), ('Desistente', 'Desistente/Evasão Escolar'), ('Transferido', 'Noturno')], default='Ativo', max_length=26, verbose_name='Tipo de remanejamento')),
                ('description', models.TextField(max_length=500, verbose_name='Descreva o motivo do Remanejamento. Ex.: Escola para onde o aluno será remanejado e o porquê.')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Serie_Escolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('compatibilidade_EducaCenso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.compatibilidade_educacenso')),
                ('nivel_escolar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.grauescolar')),
            ],
        ),
        migrations.CreateModel(
            name='TurmaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('turno', models.CharField(choices=[('Matutino', 'Matutino'), ('Verspertino', 'Verspertino'), ('Noturno', 'Noturno')], default=1, max_length=12)),
                ('quantidade_vagas', models.CharField(default=36, max_length=2)),
                ('turma_multiserie', models.BooleanField(default=False, null=True)),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.anoletivo')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.escola')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.serie_escolar')),
            ],
        ),
        migrations.CreateModel(
            name='Trimestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('soma_notas', models.BooleanField(default=True)),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.anoletivo')),
            ],
        ),
        migrations.CreateModel(
            name='Profissionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_especializacao', models.CharField(max_length=100)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.cargo')),
                ('nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RH.encaminhamentos')),
            ],
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada_escola', models.DateField()),
                ('data_saida_escola', models.DateField(null=True)),
                ('efetivo', models.BooleanField(default=False)),
                ('foto', models.ImageField(null=True, upload_to='')),
                ('disciplina', models.ManyToManyField(to='Gestao_Escolar.disciplina')),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.profissionais')),
                ('escolas', models.ManyToManyField(to='RH.escola')),
                ('formacao_academica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.cursos')),
                ('instituto_academico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.faculdades_ou_escolas')),
            ],
        ),
        migrations.CreateModel(
            name='PerguntasMultiplaEscolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='PerguntasAbertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('resposta', models.TextField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaObjetiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.TextField()),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='OpcaoMultiplaEscolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcao', models.CharField(max_length=200)),
                ('correta', models.BooleanField(default=False)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.perguntasmultiplaescolha')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertos', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.alunos')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.atividade')),
                ('trimestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.trimestre')),
            ],
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_matricula', models.DateField(auto_now=True)),
                ('obervacao', models.TextField(blank=True, max_length=300, null=True)),
                ('escolarizacao_fora', models.CharField(choices=[('2', 'Em hospital'), ('3', 'Em domicílio'), ('1', 'Não recebe')], default=1, max_length=1)),
                ('data_afastamento_inicio', models.DateField(null=True)),
                ('data_afastamento_fim', models.DateField(null=True)),
                ('motivo_afastamento', models.TextField(max_length=200, null=True)),
                ('calcula_media', models.BooleanField(default=True)),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.alunos')),
                ('serie_multiseriada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.serie_escolar')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.turmas')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeReutilizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_letivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.anoletivo')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.atividade')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.escola')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.turmas')),
            ],
        ),
        migrations.CreateModel(
            name='AtividadeAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertos', models.IntegerField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.alunos')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.atividade')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.profissionais')),
            ],
        ),
        migrations.AddField(
            model_name='atividade',
            name='alunos',
            field=models.ManyToManyField(through='Gestao_Escolar.AtividadeAluno', to='Gestao_Escolar.alunos'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.disciplina'),
        ),
        migrations.CreateModel(
            name='Alunos_Documentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RG', models.CharField(blank=True, default='000.000.00-00', max_length=14, null=True)),
                ('RG_emissao', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('orgao_emissor', models.CharField(blank=True, max_length=5, null=True)),
                ('renda_familiar', models.CharField(blank=True, max_length=7, null=True)),
                ('situacao_familiar', models.CharField(blank=True, max_length=15, null=True)),
                ('CPF', models.CharField(blank=True, default='000.000.000-00', max_length=14, null=True)),
                ('login_aluno', models.CharField(blank=True, max_length=10, null=True)),
                ('senha', models.CharField(blank=True, default='12345678', max_length=10, null=True)),
                ('cartao_nacional_saude_cns', models.CharField(blank=True, max_length=20, null=True)),
                ('nis', models.CharField(blank=True, max_length=20, null=True)),
                ('inep', models.CharField(blank=True, max_length=15, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('2', 'Casado'), ('6', 'União Estável'), ('5', 'Viúvo'), ('3', 'Separado'), ('1', 'Solteiro'), ('4', 'Divorciado')], max_length=13, null=True)),
                ('tipo_certidao', models.CharField(blank=True, choices=[('1', 'Nascimento'), ('3', 'Outras'), ('2', 'Casamento')], max_length=13, null=True)),
                ('numero_certidao', models.CharField(blank=True, max_length=15, null=True, verbose_name='Certidão de Nascimento (Matrícula Única)')),
                ('livro', models.CharField(blank=True, max_length=10, null=True)),
                ('folha', models.CharField(blank=True, max_length=10, null=True)),
                ('termo', models.CharField(blank=True, max_length=10, null=True)),
                ('emissao', models.DateField(blank=True, null=True)),
                ('distrito_certidao', models.CharField(blank=True, max_length=20, null=True)),
                ('cartorio', models.CharField(blank=True, max_length=100, null=True)),
                ('comarca', models.CharField(blank=True, max_length=100, null=True)),
                ('justificativa_falta_document', models.CharField(blank=True, choices=[('2', 'A escola não dispõe ou não recebeu os docum. pessoais do(a) aluno(a)'), ('1', 'o(a) aluno(a) não possui os documentos pessoais solicitados')], max_length=2, null=True, verbose_name='Justificativa da falta de documentação')),
                ('local_diferenciado', models.CharField(blank=True, choices=[('2', 'A escola não dispõe ou não recebeu os docum. pessoais do(a) aluno(a)'), ('1', 'o(a) aluno(a) não possui os documentos pessoais solicitados')], max_length=2, null=True, verbose_name='Local Diferenciado')),
                ('obito', models.BooleanField(blank=True, default=False, null=True)),
                ('data_obito', models.DateField(blank=True, null=True)),
                ('RG_UF', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='RH.uf_unidade_federativa')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.alunos')),
                ('cartorio_uf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatio_cartorio_UF', to='RH.uf_unidade_federativa')),
            ],
        ),
        migrations.AddField(
            model_name='alunos',
            name='deficiencia_aluno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.deficiencia_aluno', verbose_name='Informe se o aluno possui deficiência*'),
        ),
        migrations.AddField(
            model_name='alunos',
            name='etnia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.etnia', verbose_name='Etnia do aluno*:'),
        ),
        migrations.AddField(
            model_name='alunos',
            name='nacionalidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.nacionalidade', verbose_name='Nacionalidade*'),
        ),
        migrations.AddField(
            model_name='alunos',
            name='pais_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Gestao_Escolar.pais_origem'),
        ),
    ]
