# Generated by Django 5.0.4 on 2024-05-13 12:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0023_alter_alunos_tipo_sanguineo_and_more'),
        ('rh', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunos',
            name='CPF',
            field=models.CharField(blank=True, default='000.000.000-00', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='RG',
            field=models.CharField(blank=True, default='000.000.00-00', max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='RG_UF',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.uf_unidade_federativa'),
        ),
        migrations.AddField(
            model_name='alunos',
            name='RG_emissao',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='cartao_nacional_saude_cns',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='cartorio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='cartorio_uf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatio_cartorio_UF', to='rh.uf_unidade_federativa'),
        ),
        migrations.AddField(
            model_name='alunos',
            name='comarca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='data_obito',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='distrito_certidao',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='emissao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('6', 'União Estável'), ('5', 'Viúvo'), ('1', 'Solteiro'), ('3', 'Separado'), ('4', 'Divorciado'), ('2', 'Casado')], max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='folha',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='inep',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='justificativa_falta_document',
            field=models.CharField(blank=True, choices=[('2', 'A escola não dispõe ou não recebeu os docum. pessoais do(a) aluno(a)'), ('1', 'o(a) aluno(a) não possui os documentos pessoais solicitados')], max_length=2, null=True, verbose_name='Justificativa da falta de documentação'),
        ),
        migrations.AddField(
            model_name='alunos',
            name='livro',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='local_diferenciado',
            field=models.CharField(blank=True, choices=[('2', 'A escola não dispõe ou não recebeu os docum. pessoais do(a) aluno(a)'), ('1', 'o(a) aluno(a) não possui os documentos pessoais solicitados')], max_length=2, null=True, verbose_name='Local Diferenciado'),
        ),
        migrations.AddField(
            model_name='alunos',
            name='login_aluno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='nis',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='numero_certidao',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Certidão de Nascimento (Matrícula Única)'),
        ),
        migrations.AddField(
            model_name='alunos',
            name='obito',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='orgao_emissor',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='renda_familiar',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='senha',
            field=models.CharField(blank=True, default='12345678', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='termo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alunos',
            name='tipo_certidao',
            field=models.CharField(blank=True, choices=[('2', 'Casamento'), ('1', 'Nascimento'), ('3', 'Outras')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('2', 'A-'), ('5', 'AB+'), ('4', 'B-'), ('7', 'O+'), ('1', 'A+'), ('6', 'AB-'), ('8', 'O-'), ('0', 'Não informado'), ('3', 'B+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nivel',
            field=models.CharField(choices=[('2', 'Superior'), ('1', 'Médio')], max_length=1),
        ),
        migrations.AlterField(
            model_name='remanejamento',
            name='tipo',
            field=models.CharField(choices=[('Desistente', 'Desistente/Evasão Escolar'), ('Transferido', 'Noturno'), ('Ativo', 'Na Turma')], default='Ativo', max_length=26, verbose_name='Tipo de remanejamento'),
        ),
        migrations.DeleteModel(
            name='Alunos_Documentacao',
        ),
    ]
