# Generated by Django 5.0.4 on 2024-05-16 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0030_alter_alunos_estado_civil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turmadisciplina',
            name='professor',
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='auxiliar_classe',
            field=models.ManyToManyField(null=True, to='gestao_escolar.profissionais'),
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='professo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gradeProfessor2_related', to='gestao_escolar.profissionais'),
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='professor1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gradeProfessor1_related', to='gestao_escolar.profissionais'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('5', 'Viúvo'), ('1', 'Solteiro'), ('2', 'Casado'), ('6', 'União Estável'), ('3', 'Separado'), ('4', 'Divorciado')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='justificativa_falta_document',
            field=models.CharField(blank=True, choices=[('1', 'o(a) aluno(a) não possui os documentos pessoais solicitados'), ('2', 'A escola não dispõe ou não recebeu os docum. pessoais do(a) aluno(a)')], max_length=2, null=True, verbose_name='Justificativa da falta de documentação'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='local_diferenciado',
            field=models.CharField(blank=True, choices=[('1', 'o(a) aluno(a) não possui os documentos pessoais solicitados'), ('2', 'A escola não dispõe ou não recebeu os docum. pessoais do(a) aluno(a)')], max_length=2, null=True, verbose_name='Local Diferenciado'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('2', 'A-'), ('3', 'B+'), ('1', 'A+'), ('6', 'AB-'), ('7', 'O+'), ('0', 'Não informado'), ('5', 'AB+'), ('8', 'O-'), ('4', 'B-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nivel',
            field=models.CharField(choices=[('2', 'Superior'), ('1', 'Médio')], max_length=1),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='escolarizacao_fora',
            field=models.CharField(choices=[('3', 'Em domicílio'), ('1', 'Não recebe'), ('2', 'Em hospital')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='remanejamento',
            name='tipo',
            field=models.CharField(choices=[('Desistente', 'Desistente/Evasão Escolar'), ('Ativo', 'Na Turma'), ('Transferido', 'Noturno')], default='Ativo', max_length=26, verbose_name='Tipo de remanejamento'),
        ),
        migrations.AlterField(
            model_name='turmadisciplina',
            name='turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gradeTurma_related', to='gestao_escolar.turmas'),
        ),
    ]
