# Generated by Django 5.0.4 on 2024-05-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0036_alter_alunos_estado_civil_alter_alunos_tipo_certidao_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trimestral_Notas_Aluno',
            new_name='GestaoTurmas',
        ),
        migrations.AddField(
            model_name='turmadisciplina',
            name='reserva_tecnica',
            field=models.ManyToManyField(null=True, related_name='reservaTecnica_related', to='gestao_escolar.profissionais'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('4', 'Divorciado'), ('5', 'Viúvo'), ('1', 'Solteiro'), ('6', 'União Estável'), ('2', 'Casado'), ('3', 'Separado')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='tipo_certidao',
            field=models.CharField(blank=True, choices=[('3', 'Outras'), ('1', 'Nascimento'), ('2', 'Casamento')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('3', 'B+'), ('1', 'A+'), ('8', 'O-'), ('6', 'AB-'), ('4', 'B-'), ('7', 'O+'), ('5', 'AB+'), ('0', 'Não informado'), ('2', 'A-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nivel',
            field=models.CharField(choices=[('2', 'Superior'), ('1', 'Médio')], max_length=1),
        ),
        migrations.AlterField(
            model_name='remanejamento',
            name='tipo',
            field=models.CharField(choices=[('Desistente', 'Desistente/Evasão Escolar'), ('Transferido', 'Noturno'), ('Ativo', 'Na Turma')], default='Ativo', max_length=26, verbose_name='Tipo de remanejamento'),
        ),
        migrations.AlterField(
            model_name='turmadisciplina',
            name='auxiliar_classe',
            field=models.ManyToManyField(null=True, related_name='auxiliarClasse_related', to='gestao_escolar.profissionais'),
        ),
    ]
