# Generated by Django 5.0.4 on 2024-05-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0054_matriculas_cod_matricula_alter_alunos_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('3', 'Separado'), ('2', 'Casado'), ('6', 'União Estável'), ('5', 'Viúvo'), ('1', 'Solteiro'), ('4', 'Divorciado')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='tipo_certidao',
            field=models.CharField(blank=True, choices=[('2', 'Casamento'), ('1', 'Nascimento'), ('3', 'Outras')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('2', 'A-'), ('3', 'B+'), ('1', 'A+'), ('8', 'O-'), ('7', 'O+'), ('0', 'Não informado'), ('5', 'AB+'), ('6', 'AB-'), ('4', 'B-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='escolarizacao_fora',
            field=models.CharField(choices=[('3', 'Em domicílio'), ('1', 'Não recebe'), ('2', 'Em hospital')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='turno',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Noturno', 'Noturno'), ('Verspertino', 'Verspertino')], default=1, max_length=12),
        ),
    ]
