# Generated by Django 5.0.4 on 2024-05-31 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0085_alter_disponibilidadeprofessor_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioaula',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='horarioaula',
            name='turma_disciplina',
        ),
        migrations.RemoveField(
            model_name='disponibilidadeprofessor',
            name='dia_da_semana',
        ),
        migrations.RemoveField(
            model_name='disponibilidadeprofessor',
            name='horario_fim',
        ),
        migrations.RemoveField(
            model_name='disponibilidadeprofessor',
            name='horario_inicio',
        ),
        migrations.RemoveField(
            model_name='disponibilidadeprofessor',
            name='periodo',
        ),
        migrations.AddField(
            model_name='disponibilidadeprofessor',
            name='motivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadeprofessor',
            name='quarta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadeprofessor',
            name='quinta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadeprofessor',
            name='segunda',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadeprofessor',
            name='sexta',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadeprofessor',
            name='terca',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('2', 'Casado'), ('4', 'Divorciado'), ('1', 'Solteiro'), ('6', 'União Estável'), ('3', 'Separado'), ('5', 'Viúvo')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='tipo_certidao',
            field=models.CharField(blank=True, choices=[('1', 'Nascimento'), ('3', 'Outras'), ('2', 'Casamento')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('6', 'AB-'), ('0', 'Não informado'), ('8', 'O-'), ('2', 'A-'), ('5', 'AB+'), ('7', 'O+'), ('4', 'B-'), ('3', 'B+'), ('1', 'A+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nivel',
            field=models.CharField(choices=[('1', 'Médio'), ('2', 'Superior')], max_length=1),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='escolarizacao_fora',
            field=models.CharField(choices=[('1', 'Não recebe'), ('3', 'Em domicílio'), ('2', 'Em hospital')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='turno',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Verspertino', 'Verspertino'), ('Noturno', 'Noturno')], default=1, max_length=12),
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=10)),
                ('quarta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quarta_prof', to='gestao_escolar.profissionais')),
                ('quinta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quinta_prof', to='gestao_escolar.profissionais')),
                ('segunda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='segunda_prof', to='gestao_escolar.profissionais')),
                ('sexta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sexta_prof', to='gestao_escolar.profissionais')),
                ('terca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terca_prof', to='gestao_escolar.profissionais')),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao_escolar.turmas')),
            ],
        ),
        migrations.DeleteModel(
            name='Falta',
        ),
        migrations.DeleteModel(
            name='HorarioAula',
        ),
    ]
