# Generated by Django 5.0.4 on 2024-06-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0118_validade_horario_remove_horario_data_fim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validade_horario',
            name='nome_validade',
            field=models.CharField(default='Horario Geral', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alunos',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('4', 'Divorciado'), ('5', 'Viúvo'), ('2', 'Casado'), ('1', 'Solteiro'), ('6', 'União Estável'), ('3', 'Separado')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('1', 'A+'), ('3', 'B+'), ('8', 'O-'), ('0', 'Não informado'), ('6', 'AB-'), ('7', 'O+'), ('5', 'AB+'), ('4', 'B-'), ('2', 'A-')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nivel',
            field=models.CharField(choices=[('2', 'Superior'), ('1', 'Médio')], max_length=1),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='escolarizacao_fora',
            field=models.CharField(choices=[('1', 'Não recebe'), ('2', 'Em hospital'), ('3', 'Em domicílio')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='remanejamento',
            name='tipo',
            field=models.CharField(choices=[('Desistente', 'Desistente/Evasão Escolar'), ('Transferido', 'Noturno'), ('Ativo', 'Na Turma')], default='Ativo', max_length=26, verbose_name='Tipo de remanejamento'),
        ),
    ]
