# Generated by Django 5.0.4 on 2024-07-24 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestao_escolar', '0149_alunos_estado_alter_alunos_estado_civil_and_more'),
        ('rh', '__first__'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='nome_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.uf_unidade_federativa'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_nascimento', to='rh.uf_unidade_federativa', verbose_name='Estado onde nasceu'),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('2', 'Casado'), ('5', 'Viúvo'), ('4', 'Divorciado'), ('6', 'União Estável'), ('3', 'Separado'), ('1', 'Solteiro')], max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='tipo_sanguineo',
            field=models.CharField(choices=[('0', 'Não informado'), ('8', 'O-'), ('1', 'A+'), ('2', 'A-'), ('6', 'AB-'), ('3', 'B+'), ('4', 'B-'), ('7', 'O+'), ('5', 'AB+')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='nivel',
            field=models.CharField(choices=[('1', 'Médio'), ('2', 'Superior')], max_length=1),
        ),
        migrations.AlterField(
            model_name='matriculas',
            name='escolarizacao_fora',
            field=models.CharField(choices=[('1', 'Não recebe'), ('3', 'Em domicílio'), ('2', 'Em hospital')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='remanejamento',
            name='tipo',
            field=models.CharField(choices=[('Ativo', 'Na Turma'), ('Transferido', 'Noturno'), ('Desistente', 'Desistente/Evasão Escolar')], default='Ativo', max_length=26, verbose_name='Tipo de remanejamento'),
        ),
        migrations.AlterField(
            model_name='turmas',
            name='turno',
            field=models.CharField(choices=[('Matutino', 'Matutino'), ('Verspertino', 'Verspertino'), ('Noturno', 'Noturno')], default=1, max_length=12),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
