# Generated by Django 5.0.4 on 2024-04-22 23:40

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='message_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(max_length=100, verbose_name='Escreva o assunto da sua mensagem')),
                ('messagem', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('aberta', models.BooleanField(default=False)),
                ('foi_consultado', models.BooleanField(default=False)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('exclude_msg', models.CharField(max_length=5, null=True)),
                ('remetente', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remetente da mensagem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Pequise o nome do destinatário')),
            ],
            options={
                'ordering': ['-data_envio'],
            },
        ),
    ]
