# Generated by Django 5.0.4 on 2024-05-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_acessos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaletaCores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_primaria', models.CharField(default='primary', max_length=20)),
                ('cor_secundaria', models.CharField(default='secondary', max_length=20)),
                ('cor_sucesso', models.CharField(default='success', max_length=20)),
                ('cor_info', models.CharField(default='info', max_length=20)),
                ('cor_aviso', models.CharField(default='warning', max_length=20)),
                ('cor_perigo', models.CharField(default='danger', max_length=20)),
            ],
        ),
    ]
