# Generated by Django 5.0.4 on 2024-05-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_acessos', '0002_paletacores'),
    ]

    operations = [
        migrations.AddField(
            model_name='paletacores',
            name='cor_texto',
            field=models.CharField(default='#000', max_length=7),
        ),
        migrations.AddField(
            model_name='paletacores',
            name='nome_paleta',
            field=models.CharField(default='Paleta Branca', max_length=20),
        ),
        migrations.AlterField(
            model_name='paletacores',
            name='cor_aviso',
            field=models.CharField(default='#fff', max_length=7),
        ),
        migrations.AlterField(
            model_name='paletacores',
            name='cor_info',
            field=models.CharField(default='#fff', max_length=7),
        ),
        migrations.AlterField(
            model_name='paletacores',
            name='cor_perigo',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='paletacores',
            name='cor_primaria',
            field=models.CharField(default='#fff', max_length=7),
        ),
        migrations.AlterField(
            model_name='paletacores',
            name='cor_secundaria',
            field=models.CharField(default='#fff', max_length=7),
        ),
        migrations.AlterField(
            model_name='paletacores',
            name='cor_sucesso',
            field=models.CharField(default='#fff', max_length=7),
        ),
    ]
