# Generated by Django 5.0.4 on 2024-05-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_acessos', '0003_paletacores_cor_texto_paletacores_nome_paleta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomeclaturaJanelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Paleta Branca', max_length=20)),
            ],
        ),
    ]
