# Generated by Django 5.0.4 on 2024-05-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_acessos', '0004_nomeclaturajanelas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomeclaturajanelas',
            name='nome',
        ),
        migrations.AddField(
            model_name='nomeclaturajanelas',
            name='nome_diciplina',
            field=models.CharField(default='', max_length=20),
        ),
    ]
