# Generated by Django 5.0.4 on 2024-05-27 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_acessos', '0005_remove_nomeclaturajanelas_nome_and_more'),
        ('gestao_escolar', '0063_alter_alunos_estado_civil_alter_alunos_tipo_certidao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomeclaturajanelas',
            name='ano_letivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AnoLetivo_nomeclatura_related', to='gestao_escolar.anoletivo'),
        ),
    ]
