# Generated by Django 5.0.4 on 2024-05-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_acessos', '0006_nomeclaturajanelas_ano_letivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomeclaturajanelas',
            name='ano_letivo',
        ),
    ]
