# Generated by Django 5.0.4 on 2024-05-27 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_acessos', '0008_alter_nomeclaturajanelas_nome_diciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomeclaturajanelas',
            name='nome_diciplina',
            field=models.CharField(default='', max_length=50),
        ),
    ]
