# Generated by Django 5.0.4 on 2024-05-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_acessos', '0009_alter_nomeclaturajanelas_nome_diciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomeclaturajanelas',
            name='notas',
            field=models.CharField(default='', max_length=20),
        ),
    ]
