# Generated by Django 5.0.4 on 2024-04-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo_empregaticio',
            name='vinculo',
            field=models.CharField(choices=[('estagio', 'estagio'), ('decreto', 'Decreto'), ('efetivo', 'efetivo'), ('contrato', 'Contrato')], max_length=10, null=True),
        ),
    ]
