# Generated by Django 4.2.2 on 2023-10-16 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculo_empregaticio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('ano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RH.ano')),
            ],
        ),
    ]
