# Generated by Django 4.2.2 on 2023-10-16 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0002_vinculo_empregaticio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinculo_empregaticio',
            name='nome',
        ),
        migrations.AddField(
            model_name='vinculo_empregaticio',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RH.pessoas'),
        ),
        migrations.AddField(
            model_name='vinculo_empregaticio',
            name='vinculo',
            field=models.CharField(choices=[('estagio', 'estagio'), ('efetivo', 'efetivo'), ('contrato', 'Contrato'), ('decreto', 'Decreto')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vinculo_empregaticio',
            name='ano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RH.ano'),
        ),
    ]
