# Generated by Django 4.2.2 on 2023-10-20 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0016_alter_vinculo_empregaticio_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia_mes',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_frequencia', to='RH.escola', verbose_name='Local onde o profissional será encaminhado'),
        ),
        migrations.AlterField(
            model_name='vinculo_empregaticio',
            name='vinculo',
            field=models.CharField(choices=[('estagio', 'estagio'), ('decreto', 'Decreto'), ('efetivo', 'efetivo'), ('contrato', 'Contrato')], max_length=10, null=True),
        ),
    ]
