# Generated by Django 4.2.2 on 2023-10-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0017_alter_frequencia_mes_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencia_mes',
            name='ano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencia_ano', to='RH.ano'),
        ),
        migrations.AlterField(
            model_name='vinculo_empregaticio',
            name='vinculo',
            field=models.CharField(choices=[('decreto', 'Decreto'), ('estagio', 'estagio'), ('contrato', 'Contrato'), ('efetivo', 'efetivo')], max_length=10, null=True),
        ),
    ]
