# Generated by Django 4.2.2 on 2023-10-20 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0018_alter_frequencia_mes_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encaminhamentos',
            name='destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_encaminhamento', to='RH.escola', verbose_name='Local onde o profissional será encaminhado'),
        ),
        migrations.AlterField(
            model_name='vinculo_empregaticio',
            name='vinculo',
            field=models.CharField(choices=[('efetivo', 'efetivo'), ('contrato', 'Contrato'), ('decreto', 'Decreto'), ('estagio', 'estagio')], max_length=10, null=True),
        ),
    ]
