# Generated by Django 4.2.2 on 2023-10-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0024_alter_vinculo_empregaticio_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo_empregaticio',
            name='vinculo',
            field=models.CharField(choices=[('efetivo', 'efetivo'), ('estagio', 'estagio'), ('contrato', 'Contrato'), ('decreto', 'Decreto')], max_length=10, null=True),
        ),
    ]
