# Generated by Django 4.2.2 on 2023-10-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0028_alter_vinculo_empregaticio_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo_empregaticio',
            name='vinculo',
            field=models.CharField(choices=[('estagio', 'estagio'), ('contrato', 'Contrato'), ('efetivo', 'efetivo'), ('decreto', 'Decreto')], max_length=10, null=True),
        ),
    ]
