# Generated by Django 4.2.2 on 2023-10-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0031_alter_vinculo_empregaticio_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='RH.sexo'),
        ),
        migrations.AlterField(
            model_name='vinculo_empregaticio',
            name='vinculo',
            field=models.CharField(choices=[('decreto', 'Decreto'), ('contrato', 'Contrato'), ('estagio', 'estagio'), ('efetivo', 'efetivo')], max_length=10, null=True),
        ),
    ]
