# Generated by Django 4.2.2 on 2023-10-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0032_alter_pessoas_sexo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo_empregaticio',
            name='vinculo',
            field=models.CharField(choices=[('estagio', 'estagio'), ('decreto', 'Decreto'), ('efetivo', 'efetivo'), ('contrato', 'Contrato')], max_length=10, null=True),
        ),
    ]
