# Generated by Django 4.2.2 on 2023-10-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0033_alter_vinculo_empregaticio_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo_empregaticio',
            name='vinculo',
            field=models.CharField(choices=[('contrato', 'Contrato'), ('decreto', 'Decreto'), ('estagio', 'estagio'), ('efetivo', 'efetivo')], max_length=10, null=True),
        ),
    ]
