# Generated by Django 4.2.2 on 2023-11-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0054_alter_vinculo_empregaticio_vinculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinculo_empregaticio',
            name='vinculo',
            field=models.CharField(choices=[('efetivo', 'efetivo'), ('contrato', 'Contrato'), ('estagio', 'estagio'), ('decreto', 'Decreto')], max_length=10, null=True),
        ),
    ]
