# Generated by Django 5.0.4 on 2024-04-22 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rh', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria_alimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nenhuma', max_length=30, verbose_name='Escreva o nome da categoria de alimentos que deseja criar. Ex.: Vegetais')),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=30)),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('endereco', models.CharField(default='', max_length=50)),
                ('telefone', models.CharField(default='', max_length=30)),
                ('cnpj', models.CharField(default='', max_length=18, verbose_name='CNPJ')),
                ('email', models.CharField(default='', max_length=30)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Alimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome do alimento', max_length=30)),
                ('quantidade_disponivel', models.PositiveBigIntegerField(default=0)),
                ('unidade', models.CharField(max_length=10)),
                ('prefeitura', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='rh.prefeitura', verbose_name='Nome da Instituição principal')),
                ('categoria_alimento', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.categoria_alimentos')),
            ],
            options={
                'ordering': ['-quantidade_disponivel'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao_Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30, verbose_name='Tipo de movimentação:')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('quantidade', models.PositiveBigIntegerField(max_length=10)),
                ('numero_nota_fiscal', models.CharField(default='000000000', max_length=9, verbose_name='Nº da nota fiscal')),
                ('unidadeMedida', models.CharField(choices=[('litros', 'litros'), ('kg', 'kg')], max_length=10, verbose_name='Unidade de Medida')),
                ('observacoes', models.CharField(max_length=150)),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='controle_estoque.alimentos')),
                ('fornecedor_alimento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='controle_estoque.fornecedor')),
                ('local_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rh.escola')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacaoSaidaEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendamento', models.DateField()),
                ('situacao', models.BooleanField(null=True, verbose_name='Enviado')),
                ('escola_beneficiaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rh.escola')),
                ('movimentacoes_estoque', models.ManyToManyField(to='controle_estoque.movimentacao_estoque')),
            ],
        ),
    ]
