# Generated by Django 5.0.4 on 2024-04-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0005_alter_movimentacao_estoque_unidademedida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacaosaidaestoque',
            name='escola_beneficiaria',
        ),
    ]
