# Generated by Django 5.0.4 on 2024-04-26 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0006_remove_programacaosaidaestoque_escola_beneficiaria'),
        ('rh', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='programacaosaidaestoque',
            name='escola_beneficiaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.escola'),
        ),
    ]
