# Generated by Django 5.0.4 on 2024-04-26 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_estoque', '0007_programacaosaidaestoque_escola_beneficiaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programacaosaidaestoque',
            name='escola_beneficiaria',
        ),
        migrations.AlterField(
            model_name='movimentacao_estoque',
            name='unidadeMedida',
            field=models.CharField(choices=[('kg', 'kg'), ('litros', 'litros')], max_length=10, verbose_name='Unidade de Medida'),
        ),
    ]
